name: vroom
description: "Wrapping the VROOM C++ library for Dart and Flutter. (Eventually)"
repository: https://github.com/nielsenko/vroom-dart
version: 0.0.2-dev.5

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  ffigen: ^8.0.2
  lints: ^3.0.0
  test: ^1.24.9

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
