name: vroom
description: "Wrapping the VROOM C++ library for Dart and Flutter. (Eventually)"
repository: https://github.com/nielsenko/vroom-dart
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  ffigen: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
